apiVersion: v1
kind: Secret
metadata:
  name: labsecret
  namespace: bookstore-lab
  labels:
    app.k8s: bookstore-lab-secret
type: Opaque

stringData:
  DATABASE_URL: "postgresql://bookstore:bookstore_local_only@postgres.bookstore.svc.cluster.local:5432/bookstore"

